import "./styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./Provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session, // Pass the session prop here
}: {
  children: React.ReactNode;
  session: any; // Make sure to define the proper session type
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
